version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ./:/var/www

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./docker/workspace
            args:
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
                - PUID=1000
                - PGID=1000
                - TZ=UTC
        volumes_from:
            - applications
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        environment:
            - PHP_IDE_CONFIG=serverName=${APP_DOMAIN}
        tty: true
        links:
           - mysql
        restart: always

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./docker/php-fpm
            args:
                - INSTALL_XDEBUG=${INSTALL_XDEBUG}
            dockerfile: Dockerfile-70
        volumes_from:
            - applications
        expose:
            - "9000"
        links:
            - workspace
            - mysql
        environment:
            - PHP_IDE_CONFIG=serverName=${APP_DOMAIN}
        external_links:
            - nginx:${APP_DOMAIN}
        restart: always


### MySQL Container #########################################

    mysql:
        build:
            context: ./docker/mysql
            args:
                - MYSQL_DATABASE=${DB_DATABASE}
                - MYSQL_USER=${DB_USERNAME}
                - MYSQL_PASSWORD=${DB_PASSWORD}
                - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: always


### Nginx Server Container ##################################

    nginx:
        build:
            context: ./docker/nginx
        volumes_from:
            - applications
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
        environment:
            - PHP_UPSTREAM=php-fpm
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        links:
            - php-fpm
        restart: always


### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"

